language: java
jdk: openjdk12
jobs:
  include:
    - stage: test
      name: "Unit Tests"
      script: mvn test -DfailIfNoTests=false -Dtest=!org.fabasoad.db.* -B
    - name: "Integration Tests"
      services: mysql
      before_script:
        - mvn -pl sma-site-db exec:java -Dexec.args="mysql 127.0.0.1 3306 root $(printenv MYSQL_ROOT_PASSWORD)"
      script: mvn -pl sma-site-db test -B
    - stage: install
      name: "Installation"
      script:
        - mvn install -DskipTests -P frontend-install
        - mvn install -DskipTests -P frontend-build
    - stage: deploy
      name: "Deploy"
      if: branch = master
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        skip_cleanup: true
        draft: true