language: java
jdk: openjdk12
jobs:
  include:
    - stage: test
      name: "Unit Tests"
      script: mvn test -DfailIfNoTests=false -Dtest=!org.fabasoad.db.* -B
    - name: "Integration Tests"
      services: mysql
      before_script:
        - mysql -e 'CREATE DATABASE sma_db;'
        - mysql -u root -p sma_db --password=""m < sma-site-db/src/main/resources/db/mysql/scripts/init.sql
      script: mvn -pl sma-site-db test -B
    - stage: install
      name: "Installation"
      script:
        - mvn install -DskipTests -P frontend-install
        - mvn install -DskipTests -P frontend-build