language: java
jdk: openjdk12
jobs:
  include:
    - stage: tests
      name: "Unit Tests"
      script: mvn test -DfailIfNoTests=false -Dtest=!org.fabasoad.db.* -B
    - name: "Integration Tests"
      services: mysql
      before_script:
        - mvn -pl sma-site-db exec:java -Dexec.args="mysql 127.0.0.1 3306 root $(printenv MYSQL_ROOT_PASSWORD)"
      script: mvn -pl sma-site-db test -B
    - stage: install
      name: "Installation"
      script:
        - mvn install -DskipTests -P frontend-install
        - mvn install -DskipTests -P frontend-build
    - stage: deploy
      name: "Deploy"
      script: true
      if: tag IS present
      before_deploy:
        - export RELEASE_FILE=$(ls sma-site-webapp/target/sma-site-webapp-*.war)
        - echo "Deploying ${RELEASE_FILE} to GitHub..."
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file: "${RELEASE_FILE}"
        skip_cleanup: true
        on:
          tags: true