language: java
jdk: openjdk12
script: mvn test -DfailIfNoTests=false -Dtest=!org.fabasoad.db.* -B
after_script:
  - mvn install -DskipTests -P frontend-install
  - mvn install -DskipTests -P frontend-build