CREATE TABLE IF NOT EXISTS SMA_PARAMS (
  SP_PROP_NAME VARCHAR(255),
  SP_PROP_VALUE VARCHAR(255) NOT NULL,
  PRIMARY KEY (SP_PROP_NAME)
);

INSERT IGNORE INTO SMA_PARAMS VALUES ('SMA_MAIN_BODY', '');
INSERT IGNORE INTO SMA_PARAMS VALUES ('SMA_CONTACTS_BODY', '');
INSERT IGNORE INTO SMA_PARAMS VALUES ('SMA_COMPANY_NAME', 'Southern Marine Agency');
INSERT IGNORE INTO SMA_PARAMS VALUES ('SMA_FOOTER_YEAR', '2017');

CREATE TABLE IF NOT EXISTS SMA_NEWS (
  SN_ID INTEGER AUTO_INCREMENT,
  SN_TITLE VARCHAR(255) NOT NULL,
  SN_BODY VARCHAR(255) NOT NULL,
  SN_CREATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (SN_ID)
);

CREATE TABLE IF NOT EXISTS SMA_VACANCIES (
  SV_ID INTEGER AUTO_INCREMENT,
  SV_RANK VARCHAR(255) NOT NULL,
  SV_VESSEL_TYPE VARCHAR(255),
  SV_JOINING_DATE DATE NOT NULL,
  SV_CONTRACT_DURATION VARCHAR(255) NOT NULL,
  SV_NATIONALITY VARCHAR(255) NOT NULL,
  SV_WAGE VARCHAR(255) NOT NULL,
  SV_DESCRIPTION VARCHAR(255) NOT NULL,
  PRIMARY KEY (SV_ID)
);

CREATE TABLE IF NOT EXISTS SMA_REFERENCES (
  SR_ID INTEGER AUTO_INCREMENT,
  SR_TITLE VARCHAR(255),
  SR_FILE_NAME VARCHAR(255) NOT NULL,
  PRIMARY KEY (SR_ID)
);

CREATE TABLE IF NOT EXISTS SMA_APPLICATION_FORMS (
  SAF_ID INTEGER AUTO_INCREMENT,
  SAF_SENDER_NAME VARCHAR(255),
  SAF_FILE_NAME VARCHAR(255) NOT NULL,
  PRIMARY KEY (SAF_ID)
);

CREATE TABLE IF NOT EXISTS SMA_USER_ROLES (
  SUR_ID INTEGER AUTO_INCREMENT,
  SUR_NAME VARCHAR(255) NOT NULL,
  PRIMARY KEY (SUR_ID)
);

INSERT IGNORE INTO SMA_USER_ROLES (SUR_NAME) VALUES ('admin');
INSERT IGNORE INTO SMA_USER_ROLES (SUR_NAME) VALUES ('basic');

CREATE TABLE IF NOT EXISTS SMA_USERS (
  SU_ID INTEGER AUTO_INCREMENT,
  SU_EMAIL VARCHAR(255) NOT NULL,
  SU_PASSWORD VARCHAR(255),
  CONSTRAINT SU_EMAIL_UNIQUE UNIQUE (SU_EMAIL),
  PRIMARY KEY (SU_ID)
);

INSERT IGNORE INTO SMA_USERS (SU_EMAIL, SU_PASSWORD)
  VALUES ('bulas.business@gmail.com', '$2a$12$n7qQPvkwjpJLWNgISDf4YeKmWOXVHf1ehW7OlagHbuImBveqEGWZ.');
INSERT IGNORE INTO SMA_USERS (SU_EMAIL, SU_PASSWORD)
  VALUES ('fabasoad@gmail.com', '$2a$12$n7qQPvkwjpJLWNgISDf4YeKmWOXVHf1ehW7OlagHbuImBveqEGWZ.');

CREATE TABLE IF NOT EXISTS SMA_USERS_ROLES_RELATIONS (
  SURR_USER_ID INTEGER,
  SURR_ROLE_ID INTEGER,
  CONSTRAINT SURR_PK PRIMARY KEY (SURR_USER_ID, SURR_ROLE_ID),
  FOREIGN KEY (SURR_USER_ID) REFERENCES SMA_USERS (SU_ID),
  FOREIGN KEY (SURR_ROLE_ID) REFERENCES SMA_USER_ROLES (SUR_ID)
);

INSERT IGNORE INTO SMA_USERS_ROLES_RELATIONS (SURR_USER_ID, SURR_ROLE_ID)
  SELECT SU_ID, SUR_ID FROM SMA_USERS, SMA_USER_ROLES
  WHERE SMA_USERS.SU_EMAIL IN ('bulas.business@gmail.com', 'fabasoad@gmail.com') AND SMA_USER_ROLES.SUR_NAME = 'admin';

CREATE TABLE IF NOT EXISTS SMA_CAROUSEL_IMAGES (
  SCI_ID INTEGER AUTO_INCREMENT,
  SCI_TITLE VARCHAR(255),
  SCI_FILE_NAME VARCHAR(255) NOT NULL,
  PRIMARY KEY (SCI_ID)
);