CREATE TABLE IF NOT EXISTS SMA_PARAMS (
  SP_PROP_NAME TEXT PRIMARY KEY,
  SP_PROP_VALUE TEXT NOT NULL
);

INSERT OR IGNORE INTO SMA_PARAMS VALUES ('SMA_MAIN_BODY', '');
INSERT OR IGNORE INTO SMA_PARAMS VALUES ('SMA_CONTACTS_BODY', '');

CREATE TABLE IF NOT EXISTS SMA_NEWS (
  SN_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  SN_TITLE TEXT NOT NULL,
  SN_BODY TEXT NOT NULL,
  SN_CREATION_DATE DATETIME DEFAULT (DATETIME('now'))
);

CREATE TABLE IF NOT EXISTS SMA_VACANCIES (
  SV_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  SV_RANK TEXT NOT NULL,
  SV_VESSEL_TYPE TEXT,
  SV_JOINING_DATE DATE NOT NULL,
  SV_CONTRACT_DURATION TEXT NOT NULL,
  SV_NATIONALITY TEXT NOT NULL,
  SV_WAGE TEXT NOT NULL,
  SV_DESCRIPTION TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS SMA_REFERENCES (
  SR_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  SR_TITLE TEXT NOT NULL,
  SR_FILE_NAME TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS SMA_APPLICATION_FORMS (
  SAF_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  SAF_FILE_NAME TEXT NOT NULL
);