---
name: Integration Tests

on:
  push:
    branches:
      - 'main'
      - 'bugfix/**'
      - 'bump/patch-*'
      - 'feature/**'
      - 'dependabot/**'

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  functional_tests:
    name: Run script
    timeout-minutes: 15
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.ref }}
      - name: Compile
        run: mvn compile
      - name: Build
        run: mvn -pl sma-site-db exec:java -Dexec.args="mysql 127.0.0.1 3306 root $(printenv MYSQL_ROOT_PASSWORD)"
      - name: Install
        run: |
          mvn install -Dmaven.test.skip=true -P frontend-install
          mvn install -Dmaven.test.skip=true -P frontend-build
