---
name: Security Tests

on:
  push:
    branches:
      - 'main'
      - 'bugfix/**'
      - 'bump/patch-*'
      - 'feature/**'
      - 'dependabot/**'
  schedule:
    - cron: '25 2 * * 6'

jobs:
  snyk_tests:
    name: Snyk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.ref }}
      - uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_API_TOKEN }}
  codeql_tests:
    name: CodeQL
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: ['java']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '15'
      - name: Build
        run: mvn clean install -Dmaven.test.skip=true -B
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
