---
name: Unit Tests

on:
  push:
    branches:
      - 'main'
      - 'bugfix/**'
      - 'bump/patch-*'
      - 'feature/**'
      - 'dependabot/**'

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  functional_tests:
    name: Run script
    timeout-minutes: 15
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.ref }}
      - name: Compile
        run: mvn compile
      - name: Test
        run: mvn test verify
